### ISSUE TITLE
kotlin-compiler-embeddable-1.4.30

### ISSUE THREAD

**Issue by ghost** [project-mirai/mirai-console-plugin-template#11]
构建时无法获取依赖
`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileKotlin'.
> Could not resolve all files for configuration ':kotlinCompilerClasspath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-compiler-embeddable:1.4.30.
     Required by:
         project :
      > Could not resolve org.jetbrains.kotlin:kotlin-compiler-embeddable:1.4.30.
         > Could not get resource 'https://dl.bintray.com/him188moe/mirai/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.4.30/kotlin-compiler-embeddable-1.4.30.pom'.
            > Could not GET 'https://dl.bintray.com/him188moe/mirai/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.4.30/kotlin-compiler-embeddable-1.4.30.pom'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s`
这是我的问题吗,或者应该如何解决(

**Comment by Him188** [comment]
删除 `jcenter()`

**Comment by BJ4501** [comment]
使用全新机器搭建环境，构建最新template示例项目，依旧会有此问题。

`Could not HEAD 'https://dl.bintray.com/him188moe/mirai/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.4.30/kotlin-compiler-embeddable-1.4.30.pom'. Received status code 502 from server: Bad Gateway`

build.gradle.kts
```
repositories {
    mavenLocal()
    maven("https://maven.aliyun.com/repository/public") // 阿里云国内代理仓库
    mavenCentral()
}
```

settings.gradle.kts
```
pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        mavenCentral()
        maven("https://dl.bintray.com/kotlin/kotlin-eap")
    }
}
```

机器环境：
Oracle JDK 11.0.14

即使将`maven("https://dl.bintray.com/kotlin/kotlin-eap")`注释掉，也没有效果。

**Comment by Him188** [comment]
网络问题

尝试更新版本

id("net.mamoe.mirai-console") version "2.6.6"

更新为 2.9.0

**Comment by BJ4501** [comment]
> 
版本更新为2.9.0后恢复正常。非常感谢。
