### ISSUE TITLE
建议将 RunMiraiKt.run.xml 的工作目录改为 build

### ISSUE THREAD

**Issue by shirok1** [project-mirai/mirai-console-plugin-template#14]
- 避免 run 目录被删除后无法运行
- 避免原 .gitignore 文件被删除后未手动添加 run 目录至 ignore，将机密错误提交到仓库

**Comment by shirok1** [comment]
第二点的意思是，手动建立 ignore 文件时基本都会加上 build 目录。

**Comment by Him188** [comment]
build 会在 `./gradlew clean` 时清空, 届时 deviceInfo.json 等就被清除了, 然后需要重新验证. 如果你不喜欢使用 run, 可以自行修改该目录
