### ISSUE TITLE
版本还是2.0-RC,有点老了?

### ISSUE THREAD

**Issue by Nambers** [project-mirai/mirai-console-plugin-template#4]
版本好像还是2.0-RC，现在已经2.2.0了，貌似有点老了
或者没时间更的话用我这个替一下？<https://github.com/Nambers/mirai_kotlin_example>  或我有时间提个PR?
hhhh

**Comment by Him188** [comment]
其实更换版本号就好了

**Comment by Nambers** [comment]
> 其实更换版本号就好了

hhhh 确实，不过可能会存在理解上的门槛吧在刚入门的时候
