### ISSUE TITLE
idea的kotlin插件更新后出现两个错误

### ISSUE THREAD

**Issue by Mjx121418** [project-mirai/mirai-console-plugin-template#7]
刚才idea的kotlin插件自动更新了，重启idea之后再打开这个项目就多了两个错误，分别是
Object 'MyPluginMain' is not abstract and does not implement abstract base class member public abstract fun getParentPermission(): Permission defined in net.mamoe.mirai.console.plugin.jvm.KotlinPlugin
和
Inherited platform declarations clash: The following declarations have the same JVM signature (getParentPermission()Lnet/mamoe/mirai/console/permission/Permission;): fun <get-parentPermission>(): Permission defined in org.example.my.plugin.MyPluginMain fun getParentPermission(): Permission defined in org.example.my.plugin.MyPluginMain
<img width="1398" alt="Screen Shot 2021-02-27 at 23 12 18" src="https://user-images.githubusercontent.com/16516119/109391292-490f8d80-7951-11eb-87f7-d5451435c54f.png">

**Comment by Him188** [comment]
请 File -> Clear Caches and Restart
